[[colors.indexed_colors]]
color = "0xf4a261"
index = 16

[[colors.indexed_colors]]
color = "0xd67ad2"
index = 17

[colors.bright]
black = "0x575860"
blue = "0x86abdc"
cyan = "0x7ad4d6"
green = "0x8ebaa4"
magenta = "0xbaa1e2"
red = "0xd16983"
white = "0xe4e4e5"
yellow = "0xe0c989"

[colors.normal]
black = "0x393b44"
blue = "0x719cd6"
cyan = "0x63cdcf"
green = "0x81b29a"
magenta = "0x9d79d6"
red = "0xc94f6d"
white = "0xdfdfe0"
yellow = "0xdbc074"

[colors.primary]
background = "0x192330"
foreground = "0xcdcecf"

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000

[window]
decorations = "none"
opacity = 0.94
startup_mode = "Maximized"
padding = {x =  0, y = 0}
option_as_alt = "OnlyLeft"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "ArrowLeft", mods = "Option", chars = "\u001bb" },    # Jump left a word
  { key = "ArrowRight", mods = "Option", chars = "\u001bf" },   # Jump right a word 
  { key = "ArrowLeft", mods = "Command", chars = "\u001bOH" },  # Start of line
  { key = "ArrowRight", mods = "Command", chars = "\u001bOF" }, # End of line 
  { key = "Backspace", mods = "Command", chars = "\u0015" },    # delete word/line
]
