[colors.primary]
background = "0x1b1e28"
foreground = "0xa6accd"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "0x1b1e28"
background = "0xadd7ff"

[colors.search.focused_match]
foreground = "0x1b1e28"
background = "0xadd7ff"

[colors.selection]
text = "CellForeground"
background = "0x303340"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.normal]
black = "0x1b1e28"
red = "0xd0679d"
green = "0x5de4c7"
yellow = "0xfffac2"
blue = "0x89ddff"
magenta = "0xfcc5e9"
cyan = "0xadd7ff"
white = "0xffffff"

[colors.bright]
black = "0xa6accd"
red = "0xd0679d"
green = "0x5de4c7"
yellow = "0xfffac2"
blue = "0xadd7ff"
magenta = "0xfae4fc"
cyan = "0x89ddff"
white = "0xffffff"

[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"
LANG = "en_US.UTF-8"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 8

[scrolling]
history = 5000

[window]
decorations = "none"
opacity = 0.95
startup_mode = "Maximized"
padding = {x =  0, y = 0}
option_as_alt = "OnlyLeft"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "ArrowLeft", mods = "Option", chars = "\u001bb" },    # Jump left a word
  { key = "ArrowRight", mods = "Option", chars = "\u001bf" },   # Jump right a word 
  { key = "ArrowLeft", mods = "Command", chars = "\u001bOH" },  # Start of line
  { key = "ArrowRight", mods = "Command", chars = "\u001bOF" }, # End of line 
  { key = "Backspace", mods = "Command", chars = "\u0015" },    # delete word/line
]
