# Colors (Oxocarbon)
# Source https://vimcolorschemes.com/nyoom-engineering/oxocarbon.nvim

# Default colors
[colors.primary]
background = '#1b1b1b'
foreground = '#ffffff'

[colors.cursor]
text = '#161616' 
cursor = '#78a9ff'

# Normal colors
[colors.normal]
black   = '#161616'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ff7eb6'
blue    = '#33b1ff'
magenta = '#be95ff'
cyan    = '#3ddbd9'   
white   = '#ffffff'  

# Bright colors
[colors.bright]
black   = '#525252'
red     = '#ee5396'
green   = '#42be65'
yellow  = '#ff7eb6'
blue    = '#33b1ff'
magenta = '#be95ff'
cyan    = '#3ddbd9'   
white   = '#ffffff'  


[cursor]
blink_interval = 500
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 4

[scrolling]
history = 5000

[window]
decorations = "none"
opacity = 0.94
startup_mode = "Maximized"
padding = {x =  0, y = 0}
option_as_alt = "OnlyLeft"

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
  { key = "ArrowLeft", mods = "Option", chars = "\u001bb" },    # Jump left a word
  { key = "ArrowRight", mods = "Option", chars = "\u001bf" },   # Jump right a word 
  { key = "ArrowLeft", mods = "Command", chars = "\u001bOH" },  # Start of line
  { key = "ArrowRight", mods = "Command", chars = "\u001bOF" }, # End of line 
  { key = "Backspace", mods = "Command", chars = "\u0015" },    # delete word/line
]
