# Core CLI / dev tooling — always installed by setups/mac/mac-setup.sh.
# GUI apps live in Brewfile.apps (opt-in with --apps).

tap "felixkratz/formulae"
tap "git-chglog/git-chglog"
tap "jankuss/genq"
tap "jesseduffield/lazydocker"
tap "julien-cpsn/atac"
tap "leoafarias/fvm"
tap "nikitabobko/tap"
tap "wix-incubator/brew"

# ── shell ────────────────────────────────────────────────────────────────────
brew "bat"
brew "coreutils"
brew "eza"
brew "fd"
brew "fzf"
brew "gnu-sed"
brew "htop"
brew "jq"
brew "pure"
brew "ripgrep"
brew "rlwrap"
brew "sesh"
brew "stow"
brew "the_silver_searcher"
brew "tlrc"
brew "tmux"
brew "tmuxp"
brew "tree"
brew "wget"
brew "yq"
brew "zoxide"
brew "zsh-autosuggestions"
brew "pam-reattach" # Touch ID for sudo inside tmux

# ── git ──────────────────────────────────────────────────────────────────────
brew "gh"
brew "git"
brew "git-delta"
brew "git-flow"
brew "gnupg"
brew "lazygit"
brew "worktrunk"
brew "git-chglog/git-chglog/git-chglog"
brew "hunk"

# ── build toolchain (neovim from source, asdf python/ruby builds) ───────────
brew "asdf"
brew "automake"
brew "cmake"
brew "gettext"
brew "libtool"
brew "libyaml"
brew "make"
brew "meson"
brew "ninja"
brew "openssl@3"
brew "pkgconf"
brew "readline"
brew "sqlite"
brew "tcl-tk"
brew "xz"
brew "zlib"
brew "luarocks"

# ── dev ──────────────────────────────────────────────────────────────────────
brew "aichat"
brew "azure-cli"
brew "cabal-install"
brew "lcov"
brew "maven"
brew "mysql@8.4"
brew "nginx"
brew "pandoc"
brew "perl"
brew "podman"
brew "postgresql@14"
brew "rtk"
brew "shellcheck"
brew "watchman"
brew "zrok"
brew "jankuss/genq/genq"
brew "jesseduffield/lazydocker/lazydocker"
brew "julien-cpsn/atac/atac"

# ── mobile (Flutter / iOS / Android) ─────────────────────────────────────────
brew "apktool"
brew "bundletool"
brew "cocoapods"
brew "pidcat"
brew "xcbeautify"
brew "xcode-build-server"
brew "leoafarias/fvm/fvm"
brew "wix-incubator/brew/applesimutils"
cask "android-platform-tools"

# ── misc / libs ──────────────────────────────────────────────────────────────
brew "asciinema"
brew "doggo"
brew "fswatch"
brew "graphicsmagick"
brew "gtk+"
brew "gtk-mac-integration"
brew "hashcat"
brew "hcxtools"
brew "jsonpp"
brew "libdap"
brew "libnotify"
brew "librsvg"
brew "libspatialite"
brew "m-cli"
brew "mas"
brew "mpv"
brew "numpy"
brew "openconnect"
brew "poppler"
brew "qt"
brew "slides"
brew "sshs"
brew "telnet"

# ── desktop: window manager, terminals, fonts ────────────────────────────────
brew "felixkratz/formulae/borders" # started from aerospace.toml
cask "nikitabobko/tap/aerospace"
cask "alacritty"
cask "kitty"
cask "wezterm"
cask "git-credential-manager"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-maple-mono-nf"
