require('impatient').enable_profile()
require('rmc.theme')
require('rmc.treesitter')
require('rmc.lsp')
require('rmc.lsp-saga')
require('rmc.telescope')
require('rmc.lualine')
require('rmc.gitsigns')
require('rmc.dap')
require('rmc.projects')
require('rmc.projectionist')
require('rmc.harpoon')
require('rmc.utils')
require("bufresize").setup()

